### ISSUE TITLE
What would you recommend is the best way for someone to change career and break into a coding dev job?

### ISSUE THREAD

**Issue by MojoJojo86** [danrosenthal/ama#1]

**Comment by danrosenthal** [comment]
@MojoJojo86 this is a tough question to be prescriptive about, but as someone who has made that career change, I can tell you what worked for me.

I graduated university with a degree in English literature and journalism, so I started off my career writing. While working as a copywriter, I enrolled in a community college web design program. This allowed me to move into roles that involved more web development. For example, I split my time working at Uncrate between writing articles and rebuilding the frontend of [uncrate.com](https://uncrate.com/)).

What really made the difference was leaving my job and enrolling in a six-month apprenticeship program at a [local agency](https://seesparkbox.com/). I can't recommend apprenticeships enough. They combine the benefits of mentorship and dedicated learning time with paid employment and real-world experience. My apprenticeship taught me the skills I needed to land a job as a frontend developer at an agency, and from there it was history.

**Comment by danrosenthal** [comment]
We also built an [apprenticeships marketplace](https://apprentice.at/) as our apprenticeship group project. It lists a bunch of available apprenticeships in a couple different subfields, and provides some useful info on what apprenticing is all about.
